### ISSUE TITLE
app_resource_manager_get should return fail

### ISSUE THREAD

**Issue by myroot** [dalihub/tizenfx-stub#19]
app_resource_manager_get should return correct value with non-error code

if you can't get path it should return fail

https://github.com/dalihub/tizenfx-stub/blob/2ced0d9728e602b8770320f43b6f94bdf97f5c13/src/app-common.c#L258-L263

``` c
 int app_resource_manager_get(app_resource_e type, const char *id, char **path) 
 {
   return -1; 
 } 
```

**Comment by hinohie** [comment]
We don't have plan to support `Tizen.Applications.ResourceManager.GetPath` API correctly now.

This project is just for stub repo to run dali / NUI application, not Tizen application.
